CREATE TABLE `HovesAdmin`.`Companies` (
    `Name` TEXT NOT NULL ,
    `DB_Name` TEXT NOT NULL ,
    `Adate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `ID` TEXT NOT NULL ,
    `RID` INT NOT NULL AUTO_INCREMENT ,
    PRIMARY KEY (`RID`)
) ENGINE = InnoDB;

CREATE TABLE `HovesAdmin`.`Users` (
    `Name` TEXT NOT NULL ,
    `CompID` TEXT NOT NULL ,
    `Username` TEXT NOT NULL ,
    `Pass` TEXT NOT NULL ,
    `adate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `ID` TEXT NOT NULL , 
    `RID` INT NOT NULL AUTO_INCREMENT ,
    PRIMARY KEY (`RID`)
) ENGINE = InnoDB;

CREATE TABLE `HovesAdmin`.`LoginAuth` (
    `Token` TEXT NOT NULL ,
    `Expire` TIMESTAMP NOT NULL ,
    `UserID` TEXT NOT NULL ,
    `CompID` TEXT NOT NULL ,
    `IP` TEXT NOT NULL ,
    `Adate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `ID` INT NOT NULL AUTO_INCREMENT ,
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB;


CREATE TABLE `HovesAdmin`.`CompCreateAuth` (
    `Token` TEXT NOT NULL ,
    `Expire` TIMESTAMP NOT NULL ,
    `Adate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `ID` INT NOT NULL AUTO_INCREMENT ,
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB;